"""Train and export a compact binary detector using source-disjoint validation.

This is detection of recording labels, not a field event detector. The complete
FFT frontend and classifier are implemented in C++ for an Arduino Sense target.
"""
from __future__ import annotations
from pathlib import Path
import json
import time
import subprocess
import joblib
import torch
from torch import nn
import numpy as np
import pandas as pd
from scipy.special import expit
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import roc_auc_score

import arduino_frontend as frontend
from improve_device import (ROOT, SEED, atomic_json, file_hash, signature, weights,
                            split_calibration, check_disjoint, detector_statistics, operating_threshold)

OUT = ROOT / "results/arduino"
CACHE = ROOT / "data/cache"
NAMES = ["Logística streaming", "Árvore compacta", "Floresta compacta", "Rede neural 16 unidades"]
FAMILIES = {"Energia relativa 125–1125 Hz": list(range(8)),
            "Energia relativa 1125–4000 Hz": list(range(8,31)),
            "Variação temporal das bandas": list(range(31,62)),
            "Flatness espectral": [62,63], "Pico 219–875 Hz": [64,65,66,67]}

from arduino_models import TinyPresenceMLP

def model_for(index):
    if index == 0:
        return make_pipeline(StandardScaler(), LogisticRegression(C=.1,max_iter=1500,random_state=SEED))
    if index == 1:
        return DecisionTreeClassifier(max_depth=6,min_samples_leaf=20,random_state=SEED)
    if index==2:
        return RandomForestClassifier(n_estimators=32,max_depth=5,min_samples_leaf=20,
                                      max_features=.7,n_jobs=4,random_state=SEED)
    return TinyPresenceMLP()

def fit(model, x, y, w, validation=None, fixed_epochs=None):
    if isinstance(model,TinyPresenceMLP): model.fit(x,y,w,validation=validation,fixed_epochs=fixed_epochs)
    elif hasattr(model,"steps"): model.fit(x,y,logisticregression__sample_weight=w)
    else: model.fit(x,y,sample_weight=w)
    return model

def score(model,x):
    if hasattr(model,"decision_function"): return model.decision_function(x)
    p=np.clip(model.predict_proba(x)[:,1],1e-6,1-1e-6)
    return np.log(p/(1-p))

def calibrated(bundle,x):
    return expit(bundle["calibration_slope"]*score(bundle["model"],x)+bundle["calibration_bias"])

def prepare():
    OUT.mkdir(parents=True,exist_ok=True);(OUT/"models").mkdir(exist_ok=True)
    segments=pd.read_csv(ROOT/"results/segments.csv")
    input_manifest=json.loads((CACHE/"features_manifest.json").read_text())
    identity=signature(dict(source=input_manifest["fingerprint"],version=frontend.VERSION,
                            features=frontend.FEATURE_NAMES,frontend_sha256=file_hash(ROOT/"arduino_frontend.py")))
    path=CACHE/"arduino_features.npy"; marker=CACHE/"arduino_features.json"
    if path.exists() and marker.exists() and json.loads(marker.read_text())["signature"]==identity:
        x=np.load(path)
    else:
        waves=np.load(CACHE/"waves.npy",mmap_mode="r"); blocks=[]
        for start in range(0,len(segments),128):
            blocks.append(frontend.features(waves[start:start+128]))
            if start%2048==0: print(f"Frontend Arduino: {start}/{len(segments)}",flush=True)
        x=np.concatenate(blocks);np.save(path,x)
        atomic_json(marker,dict(signature=identity,columns=frontend.FEATURE_NAMES,version=frontend.VERSION))
    assert x.shape==(len(segments),len(frontend.FEATURE_NAMES)) and np.isfinite(x).all()
    return segments,x,identity

def bootstrap_sources(frame):
    table=frame.assign(target=frame.label.ne("noise")).groupby("group").agg(
        positive=("target","first"),fraction=("detected","mean"))
    rng=np.random.default_rng(SEED); result={}
    for name,mask in [("source_recall",table.positive),("source_false_positive_rate",~table.positive)]:
        values=table.loc[mask,"fraction"].to_numpy()
        draws=np.array([rng.choice(values,len(values),replace=True).mean() for _ in range(2000)])
        result[name+"_ci_low"],result[name+"_ci_high"]=np.quantile(draws,[.025,.975]).tolist()
    return result

def export_header(bundle,fold):
    model=bundle["model"];folder=ROOT/"firmware/MosquitoPresence"
    prefix="neural" if isinstance(model,TinyPresenceMLP) else "linear" if hasattr(model,"steps") else "trees"
    for obsolete in [name for name in ["neural","linear","trees"] if name!=prefix]:
        (OUT/"models"/f"{obsolete}_fold{fold}.npz").unlink(missing_ok=True)
    path=folder/("PresenceModel.h" if fold==0 else f"PresenceModelFold{fold}.h")
    lines=["// Generated by train_arduino.py. Fold-specific prototype; no field validation.",
           "#ifndef MOSQUITO_PRESENCE_MODEL_H", "#define MOSQUITO_PRESENCE_MODEL_H",
           '#include "StreamingFeatures.h"', "namespace mosquito {",
           f"static const float kConservativeThreshold={float(bundle['threshold_05']):.9g}f;",
           f"static const float kModerateThreshold={float(bundle['threshold_10']):.9g}f;",
           "static const float kBalancedThreshold=0.5f;"]
    def literal(value):
        s=f"{float(value):.9g}"
        if "." not in s and "e" not in s: s+=".0"
        return s+"f"
    # Avoid invalid C literals such as 1f for all-reject operating points.
    lines[5]="static const float kConservativeThreshold="+literal(bundle["threshold_05"])+";"
    lines[6]="static const float kModerateThreshold="+literal(bundle["threshold_10"])+";"
    numeric_bytes=0
    if isinstance(model,TinyPresenceMLP):
        coef=model.w1/model.scaler.scale_[None]
        bias=model.b1-coef@model.scaler.mean_
        lines += ["static const float kHiddenWeights[16][kFeatureCount]={"]
        lines += ["  {"+",".join(literal(v) for v in row)+"}," for row in coef]
        lines += ["};", "static const float kHiddenBias[16]={"+",".join(literal(v) for v in bias)+"};",
                  "static const float kOutputWeights[16]={"+",".join(literal(v) for v in model.w2)+"};",
                  "inline float rawScore(const float* x) {", "  float result="+literal(model.b2)+";",
                  "  for(uint8_t h=0;h<16;++h) { float value=kHiddenBias[h];",
                  "    for(uint8_t i=0;i<kFeatureCount;++i) { value+=kHiddenWeights[h][i]*x[i]; }",
                  "    if(value>0.f) result+=value*kOutputWeights[h]; }", "  return result; }"]
        numeric_bytes=4*(68*16+16+16+1)
        np.savez_compressed(OUT/"models"/f"neural_fold{fold}.npz",weights1=coef,bias1=bias,weights2=model.w2,bias2=model.b2)
    elif hasattr(model,"steps"):
        scaler,linear=model.steps[0][1],model.steps[-1][1]
        coef=linear.coef_[0]/scaler.scale_;bias=float(linear.intercept_[0]-np.dot(coef,scaler.mean_))
        lines+=["static const float kWeights[kFeatureCount]={"+",".join(literal(v) for v in coef)+"};",
                "inline float rawScore(const float* x) {", "  float value="+literal(bias)+";",
                "  for(uint8_t i=0;i<kFeatureCount;++i) { value+=kWeights[i]*x[i]; }", "  return value; }"]
        numeric_bytes=4*(len(coef)+1);np.savez_compressed(OUT/"models"/f"linear_fold{fold}.npz",weights=coef,bias=bias)
    else:
        trees=model.estimators_ if hasattr(model,"estimators_") else [model]
        nodes=[]; roots=[]
        for tree in trees:
            t=tree.tree_;offset=len(nodes);roots.append(offset)
            for n in range(t.node_count):
                left=offset+t.children_left[n] if t.children_left[n]>=0 else 0
                right=offset+t.children_right[n] if t.children_right[n]>=0 else 0
                value=t.value[n,0];p=float(value[1]/value.sum())
                nodes.append((int(t.feature[n]),left,right,float(t.threshold[n]),p))
        assert len(nodes)<65535
        lines+=["struct PresenceNode { int16_t feature; uint16_t left,right; float threshold,probability; };",
                f"static const PresenceNode kNodes[{len(nodes)}]={{"]
        lines += [f"  {{{f},{l},{r},{literal(t)},{literal(p)}}}," for f,l,r,t,p in nodes]
        lines += ["};",f"static const uint16_t kRoots[{len(roots)}]={{"+",".join(map(str,roots))+"};",
                  "inline float rawScore(const float* x) {", "  float probability=0.f;",
                  f"  for(uint16_t t=0;t<{len(roots)};++t) {{ uint16_t n=kRoots[t];",
                  "    while(kNodes[n].feature>=0) { const PresenceNode& node=kNodes[n];",
                  "      n=x[node.feature]<=node.threshold?node.left:node.right; }",
                  "    probability+=kNodes[n].probability; }",
                  f"  probability/= {len(roots)}.0f;",
                  "  probability=fminf(1.f-1e-6f,fmaxf(1e-6f,probability));",
                  "  return logf(probability/(1.f-probability)); }"]
        # ARM layout is 16 bytes/node (verified by the native/ARM compile audits).
        numeric_bytes=16*len(nodes)+2*len(roots)
        np.savez_compressed(OUT/"models"/f"trees_fold{fold}.npz",features=np.array(nodes)[:,0].astype("int16"),
                            left=np.array(nodes)[:,1].astype("uint16"),right=np.array(nodes)[:,2].astype("uint16"),
                            threshold=np.array(nodes)[:,3],probability=np.array(nodes)[:,4],roots=roots)
    lines += ["inline float presenceScore(const float* x) {",
              "  const float z="+literal(bundle["calibration_slope"])+"*rawScore(x)+"+literal(bundle["calibration_bias"])+";",
              "  return z>=0.f?1.f/(1.f+expf(-z)):expf(z)/(1.f+expf(z)); }", "} // namespace mosquito", "#endif"]
    path.write_text("\n".join(lines)+"\n")
    return dict(fold=fold,path=str(path.relative_to(ROOT)),selected_model=bundle["model_name"],
                numeric_model_bytes_estimate=numeric_bytes+20,sha256=file_hash(path))

def experiment(segments,x,identity):
    indices=np.flatnonzero(segments.fold_species.to_numpy()>=0)
    y=segments.label.ne("noise").to_numpy().astype(int)
    binary_segments=segments.assign(label=np.where(y==1,"mosquito","noise"))
    folds=segments.fold_species.to_numpy();all_frames=[]; protocols=[];exports=[];importance=[]
    for fold in range(3):
        train=indices[folds[indices]!=fold]; test=indices[folds[indices]==fold]
        fit_indices,cal=split_calibration(train,segments,SEED+fold)
        inner_fit,validation=split_calibration(fit_indices,binary_segments,SEED+100+fold)
        for a,b in [(fit_indices,cal),(fit_indices,test),(cal,test),(inner_fit,validation),(validation,test)]:
            check_disjoint(a,b,segments)
        selected=[];bundles=[]
        for candidate in range(len(NAMES)):
            path=OUT/"models"/f"candidate{candidate}_fold{fold}.joblib"
            sig=signature(dict(features=identity,protocol="compact-source-cal-2" if candidate==3 else "compact-source-cal-1",candidate=candidate,
                               params=str(model_for(candidate).get_params()),fit=fit_indices.tolist(),cal=cal.tolist(),
                               validation=validation.tolist(),test=test.tolist()))
            if path.exists() and (saved:=joblib.load(path))["signature"]==sig:
                bundle=saved["bundle"]
            else:
                print(f"Arduino: {NAMES[candidate]}, dobra {fold}",flush=True)
                begin=time.perf_counter()
                inner=fit(model_for(candidate),x[inner_fit],y[inner_fit],weights(inner_fit,y,segments),
                          validation=(x[validation],y[validation],weights(validation,y,segments)))
                auc=roc_auc_score(y[validation],score(inner,x[validation]),sample_weight=weights(validation,y,segments))
                model=fit(model_for(candidate),x[fit_indices],y[fit_indices],weights(fit_indices,y,segments),
                          fixed_epochs=getattr(inner,"best_epoch",None))
                calibration=LogisticRegression(C=10,max_iter=1000,random_state=SEED)
                calibration.fit(score(model,x[cal])[:,None],y[cal],sample_weight=weights(cal,y,segments))
                bundle=dict(model=model,model_name=NAMES[candidate],inner_validation_auc=float(auc),
                            calibration_slope=float(calibration.coef_[0,0]),calibration_bias=float(calibration.intercept_[0]),
                            training_seconds=time.perf_counter()-begin,fold=fold,
                            neural_epoch=getattr(inner,"best_epoch",None),neural_inner_history=getattr(inner,"history",None))
                p=calibrated(bundle,x[cal]); neg=cal[y[cal]==0]
                # A threshold beyond one is representable in the C++ float export.
                bundle["threshold_05"]=min(1.0001,operating_threshold(p[y[cal]==0],neg,segments,.05))
                bundle["threshold_10"]=min(1.0001,operating_threshold(p[y[cal]==0],neg,segments,.10))
                for key in ["threshold_05","threshold_10"]:
                    if bundle[key]>1: bundle[key]=1.0001
                    else: bundle[key]=float(np.nextafter(np.float32(bundle[key]),np.float32(np.inf)))
                joblib.dump(dict(signature=sig,bundle=bundle),path,compress=3)
            bundles.append(bundle);selected.append(bundle["inner_validation_auc"])
        winner=int(np.argmax(selected));exports.append(export_header(bundles[winner],fold))
        protocols.append(dict(fold=fold,selected_candidate=winner,inner_validation_auc=dict(zip(NAMES,selected)),
                              selected_name=NAMES[winner],fit_groups=segments.iloc[fit_indices].group.unique().tolist(),
                              calibration_groups=segments.iloc[cal].group.unique().tolist(),
                              inner_validation_groups=segments.iloc[validation].group.unique().tolist(),
                              test_groups=segments.iloc[test].group.unique().tolist()))
        for candidate,bundle in enumerate(bundles):
            for model_name in ([NAMES[candidate],"Escolha por validação interna"] if candidate==winner else [NAMES[candidate]]):
                p=calibrated(bundle,x[test]);
                for operating,threshold in [("Balanceado 0,5",.5),("Calibração FPR 5%",bundle["threshold_05"]),
                                            ("Calibração FPR 10%",bundle["threshold_10"])]:
                    frame=segments.iloc[test][["path","group","label","start_s"]].copy()
                    frame["model"]=model_name;frame["fold"]=fold;frame["mode"]=operating
                    frame["score"]=p;frame["threshold"]=threshold;frame["detected"]=p>=threshold
                    all_frames.append(frame)
        bundle=bundles[winner];test_weights=weights(test,y,segments)
        baseline=roc_auc_score(y[test],calibrated(bundle,x[test]),sample_weight=test_weights)
        rng=np.random.default_rng(SEED+fold)
        # Permute each family together to preserve within-family correlations.
        for family,columns in FAMILIES.items():
            for repeat in range(5):
                shuffled=x[test].copy(); permutation=rng.permutation(len(test))
                shuffled[:,columns]=x[test][permutation][:,columns]
                changed=roc_auc_score(y[test],calibrated(bundle,shuffled),sample_weight=test_weights)
                importance.append(dict(fold=fold,family=family,repeat=repeat,source_weighted_auc_drop=baseline-changed))
    predictions=pd.concat(all_frames,ignore_index=True)
    predictions.to_csv(OUT/"predictions.csv.gz",index=False,compression=dict(method="gzip",mtime=0))
    (OUT/"predictions.csv").unlink(missing_ok=True)
    rows=[];temporal=[]
    for (model,mode),frame in predictions.groupby(["model","mode"],sort=False):
        stats=detector_statistics(frame.label.ne("noise").astype(int).to_numpy(),frame.detected.to_numpy(),
                                  frame.group.to_numpy(),frame.score.to_numpy())
        rows.append(dict(model=model,mode=mode,**stats,**bootstrap_sources(frame)))
        if model=="Escolha por validação interna":
            parts=[]
            for fold,fold_frame in frame.groupby("fold"):
                current=fold_frame.sort_values(["path","start_s"]).copy()
                thresholds=current.threshold.unique();assert len(thresholds)==1
                decision,eligible=frontend.persistence(current.score,current.path,current.start_s,thresholds[0])
                current["persistent"]=decision;current["eligible"]=eligible;parts.append(current)
            current=pd.concat(parts)
            filename=f"persistence_{mode.split()[0]}{'05' if '5%' in mode else '10' if '10%' in mode else ''}.csv"
            current.to_csv(OUT/(filename+".gz"),index=False,compression=dict(method="gzip",mtime=0))
            (OUT/filename).unlink(missing_ok=True)
            subset=current.loc[current.eligible]
            if subset.label.ne("noise").any() and subset.label.eq("noise").any():
                for rule,column in [("Uma janela no subconjunto contíguo","detected"),("2 de 3 janelas contíguas","persistent")]:
                    row=detector_statistics(subset.label.ne("noise").astype(int).to_numpy(),subset[column].to_numpy(),
                                            subset.group.to_numpy())
                    temporal.append(dict(mode=mode,rule=rule,**row))
    pd.DataFrame(rows).to_csv(OUT/"metrics.csv",index=False)
    pd.DataFrame(temporal).to_csv(OUT/"persistence_metrics.csv",index=False)
    pd.DataFrame(importance).to_csv(OUT/"permutation_importance.csv",index=False)
    atomic_json(OUT/"protocol.json",dict(feature_version=frontend.VERSION,feature_signature=identity,
                feature_names=frontend.FEATURE_NAMES,frames=frontend.WINDOW_FRAMES,frame_samples=frontend.FRAME_SIZE,
                window_samples=frontend.WINDOW_SAMPLES,sample_rate=frontend.SAMPLE_RATE,window_seconds=frontend.WINDOW_SAMPLES/frontend.SAMPLE_RATE,
                calibration_prior="balanced positive/noise source groups (50/50), not field prevalence",
                model_selection="highest source-weighted ROC AUC on disjoint inner validation groups, then refit on fit groups",
                candidate_names=NAMES,outer_folds_reused_from_original=True,source_splits=protocols,exports=exports,
                field_false_alarms_per_hour_measured=False,physical_hardware_tested=False,
                event_level_labels=False,permutation_repeats=5,permutation_interpretation="predictive sensitivity, not causal attribution",
                confirmation="causal 2/3 complete windows; reset on gaps and paths; corpus contiguity interval is 1 s",
                default_firmware_fold=0,default_firmware_mode="Calibração FPR 10%",
                analysis_is_adaptive_and_exploratory=True))
    print(pd.DataFrame(rows).loc[lambda f:f.model.eq("Escolha por validação interna")].to_string(index=False),flush=True)
    return predictions

def main():
    begin=time.perf_counter();segments,x,identity=prepare()
    experiment(segments,x,identity)
    atomic_json(OUT/"execution.json",dict(elapsed_seconds=time.perf_counter()-begin,
                script_sha256=file_hash(ROOT/"train_arduino.py"),frontend_sha256=file_hash(ROOT/"arduino_frontend.py"),
                same_outer_folds_as_original=True,feature_count=x.shape[1],physical_device_tested=False))

if __name__=="__main__": main()
